version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=development
      - MYSQL_DATABASE=roebi
    ports:
      - "3306:3306"
    volumes: 
      - c:/tmp/mysql:/var/lib/mysql