version: '3.4'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:

services:
  #DataBase Service
  database:
    #Pull the latest mysql image
    image: mysql:8.0.29
    #Specify where the persisted Data should be stored
    volumes:
      - datafiles:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: roebi
  #Api  Service
  roebi:
    image: ${DOCKER_REGISTRY-}roebi
    build:
      context: .
      dockerfile: Roebi/Dockerfile
    depends_on:
      - database
    ports:
      - "44360:443"
      - "51803:80"
    restart: always
    environment:
      - DBHOST=database
      - DBPORT=3306
      - DBPASSWORD=development
      - DBNAME=roebi
      - DBUSER=root